=== sudheernand/Workspace/IndusTrainingJavaProjectXSD/target/classes/com/indus/training/xsd/Oraganization.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://organization.training.indus.com"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:org="http://organization.training.indus.com">

    <xsd:complexType name="Name">
    	<xsd:sequence>
    		<xsd:element name="firstName" type="xsd:string" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="middleName" type="xsd:string" maxOccurs="1"
    			minOccurs="0">
    		</xsd:element>
    		<xsd:element name="lastName" type="xsd:string" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="maidenName" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="name" type="org:Name"></xsd:element>

    <xsd:complexType name="houseNo">
    	<xsd:sequence>
    		<xsd:element name="streetName" type="xsd:string"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:choice>
    			<xsd:element name="aptNo" type="xsd:string"></xsd:element>
    			<xsd:element name="houseNo" type="xsd:string"></xsd:element>
    		</xsd:choice>
    		<xsd:element name="county" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="city" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="state" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="zipcode" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="country" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="Person">
    	<xsd:sequence>
    		<xsd:element name="name" type="org:Name" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="address" type="org:houseNo"
    			maxOccurs="unbounded" minOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="address" type="org:Person"></xsd:element>
</xsd:schema>

=== sudheernand/Workspace/IndusTrainingJavaProjectXSD/target/classes/com/indus/training/xsd/Oraganizatio2n.xml
<?xml version="1.0" encoding="UTF-8"?>
<org:address xmlns:org="http://organization.training.indus.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://organization.training.indus.com Oraganization.xsd ">
  <org:name>
    <org:firstName>org:firstName</org:firstName>
    <org:lastName>org:lastName</org:lastName>
  </org:name>
  <org:address>
    <org:streetName>org:streetName</org:streetName>
    <org:aptNo>org:aptNo</org:aptNo>
    <org:city>org:city</org:city>
    <org:state>org:state</org:state>
    <org:country>org:country</org:country>
  </org:address>
</org:address>
