=== sudheernand/Workspace/IndusTrainingXml/source/Employee.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee+)>
<!ELEMENT employee (id, firstName, lastName)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ATTLIST employee eid ID #REQUIRED >
<!ATTLIST employee lang (Java|C|Python) "Java" >

=== sudheernand/Workspace/IndusTrainingXml/source/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "Employee.dtd">
<employees>
	<employee eid="E1" lang="Java">
		<id>101</id>
		<firstName>bill</firstName>
		<lastName>andrew</lastName>
	</employee>

	<employee eid="E2" lang="Python">
		<id>102</id>
		<firstName>bill</firstName>
		<lastName>
			ray</lastName>
	</employee>

</employees>
